from tkinter import *
import sqlite3
from tkMessageBox import *
con=sqlite3.Connection("Project database")
cur=con.cursor()
cur.execute("create table if not exists member(EmailU varchar2(20) primary key,First name varchar2(9),Last name varchar2(9),Mobile number(11),address varchar2(30),Password varchar2(15))")
cur.execute("create table if not exists cusord(EmailU varchar2(15),orde varchar2(90),paymode varchar2(10))")
roots=Tk()
img1=PhotoImage(file="splashscreen.gif")
def fun(e):
    roots.destroy()
    root=Tk()
    root.geometry('900x600')
    Label(root,text="").grid(row=0,column=0)
    Label(root,text="").grid(row=1,column=0)
    Label(root,text="   WELCOME TO EXQUISITE.COM !!!  ",font='Times 40',fg='purple').grid(row=3,column=0,columnspan=8)
    Label(root,text="").grid(row=4,column=0)
    Label(root,text="").grid(row=5,column=0)
    Label(root,text="").grid(row=6,column=0)
    Label(root,text="").grid(row=7,column=0)
    Label(root,text="          Welcome To Exquisite.com . A place where you can find a wide range of products of your choice.",font='Times 16',fg='green').grid(row=8,column=0)
    Label(root,text="          Just order them from your PC and get it delievered to your doorstep",font='Times 16',fg='green').grid(row=9,column=0)
    def signupgui():
        rot=Tk()
        rot.geometry('550x550')
        Label(rot,text="   Fill The Following Details:- ",font='Times 18',fg='brown').grid(row=0,column=0)
        Label(rot,text="").grid(row=1,column=0)
        Label(rot,text='Enter Your Email-Id ', font='Times 15',fg='blue').grid(row=2,column=0)
        Label(rot,text="").grid(row=3,column=0)
        Label(rot,text="").grid(row=4,column=0)
        Label(rot,text='Enter First Name ', font='Times 15',fg='blue').grid(row=5,column=0)
        Label(rot,text="").grid(row=6,column=0)
        Label(rot,text="").grid(row=7,column=0)
        Label(rot,text='Enter Last Name ', font='Times 15',fg='blue').grid(row=8,column=0)
        Label(rot,text="").grid(row=9,column=0)
        Label(rot,text="").grid(row=10,column=0)
        Label(rot,text='Enter Mobile Number ', font='Times 15',fg='blue').grid(row=11,column=0)
        Label(rot,text="").grid(row=12,column=0)
        Label(rot,text="").grid(row=13,column=0)
        Label(rot,text='Enter Address ', font='Times 15',fg='blue').grid(row=14,column=0)
        Label(rot,text="").grid(row=15,column=0)
        Label(rot,text="").grid(row=16,column=0)
        Label(rot,text='Enter Password ', font='Times 15',fg='blue').grid(row=17,column=0)

        EMAIL=Entry(rot)
        EMAIL.grid(row=2,column=1)
        EFNAME=Entry(rot)
        EFNAME.grid(row=5,column=1)
        ELNAME=Entry(rot)
        ELNAME.grid(row=8,column=1)
        MOB=Entry(rot)
        MOB.grid(row=11,column=1)
        ADDRESS=Entry(rot)
        ADDRESS.grid(row=14,column=1)
        PASS=Entry(rot)
        PASS.grid(row=17,column=1)
        def INSERT():
            E=EMAIL.get()
            F=EFNAME.get()
            L=ELNAME.get()
            M=MOB.get()
            A=ADDRESS.get()
            P=PASS.get()
            d=[E,F,L,M,A,P]
            cur.execute("insert into member values (?,?,?,?,?,?)",d)
            con.commit()
        Label(rot,text="").grid(row=16,column=0)
        Label(rot,text="").grid(row=18,column=0)
        Button(rot,text='SIGNUP',font='Times 10',fg='black',command=INSERT).grid(row=19,column=1)
        rot.mainloop()

    def CHK():
        RT=Tk()
        RT.geometry("500x200")
        Label(RT,text="").grid(row=0,column=0)
        Label(RT,text=' ENTER YOUR EMAIL-ID  ',font='Times 15',fg='black').grid(row=1,column=0)
        email=Entry(RT)
        email.grid(row=1,column=1)
        def check():
            cur.execute("select * from member where EmailU=?",(email.get(),))
            s=cur.fetchone()
            if s is not None:
                showinfo('Information',s)
            else:
                Label(RT,text='Sorry Invalid Email-Id',font='Times 12',fg='red').grid(row=7,column=0)
        Label(RT,text="").grid(row=2,column=0)
        Button(RT,text=' CHECK ',fg='black',command=check).grid(row=3,column=0)
        Label(RT,text="").grid(row=4,column=0)
        Label(RT,text="").grid(row=5,column=0)   
    def login():
        ROTN=Tk()
        ROTN.geometry("600x600")
        Label(ROTN,text="").grid(row=0,column=0)
        Label(ROTN,text="").grid(row=1,column=0)
        Label(ROTN,text="   WELCOME   USER  GOOD  TO SEE  YOU !!!",font='Times 22',fg='orange').grid(row=2,column=0,columnspan=8)
        Label(ROTN,text="").grid(row=3,column=1)
        Label(ROTN,text=' Enter Your Email-Id ',font='Times 19',fg='black').grid(row=4,column=0)
        ema=Entry(ROTN)
        ema.grid(row=4,column=1)
        Label(ROTN,text="").grid(row=5,column=0)
        Label(ROTN,text="").grid(row=6,column=0)
        Label(ROTN,text=' Enter Your Password ',font='Times 19',fg='black').grid(row=7,column=0)
        pas=Entry(ROTN,show="*")
        pas.grid(row=7,column=1)
        def lgn():
            if ema.get() == "" or pas.get() == "":
                Label(ROTN,text='Please Fill The Required fields',fg='RED',font='Times 15').grid(row=12,column=0)
            else:
                cur.execute("SELECT * FROM member WHERE EmailU = ? AND Password = ?", (ema.get(), pas.get()))
                if cur.fetchone() is not None:
                    OT=Tk()
                    OT.geometry('430x550')
                    Label(OT,text="").grid(row=0,column=0)
                    Label(OT,text='  WELCOME USER !!! ',fg='violet',font='Times 23').grid(row=1,column=2,columnspan=8)
                    Label(OT,text="").grid(row=2,column=0)
                    Label(OT,text="").grid(row=3,column=0)
                    Label(OT,text='  LETS BUY SOME STUFF !!! ',fg='green',font='Times 18').grid(row=4,column=2)
                    Label(OT,text="").grid(row=5,column=0)
                    def menord():
                        R=Tk()
                        R.geometry("400x400")
                        Label(R,text="").grid(row=0,column=0)
                        Label(R,text="").grid(row=1,column=0)
                        Label(R,text=" Click View To View An Item",font='Times 20',fg='red').grid(row=2,column=0,columnspan=15)
                        Label(R,text=" Click Add To Cart To Order",font='Times 20',fg='red').grid(row=3,column=0,columnspan=15) 
                        Label(R,text='  Shirt 1').grid(row=4,column=0)
                        Label(R,text="").grid(row=5,column=0)
                        Label(R,text="").grid(row=6,column=0)
                        Label(R,text='  Shirt 2').grid(row=7,column=0)
                        Label(R,text="").grid(row=8,column=0)
                        Label(R,text="").grid(row=9,column=0)
                        Label(R,text='  Shoe 1').grid(row=10,column=0)
                        Label(R,text="").grid(row=11,column=0)
                        Label(R,text="").grid(row=12,column=0)
                        Label(R,text='  Shoe 2').grid(row=13,column=0)
                        def st1():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="MC1.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 700').grid(row=1,column=0)
                            r.mainloop()
                        def st2():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="MC2.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 800').grid(row=1,column=0)
                            r.mainloop()
                        def se1():
                            r=Toplevel()
                            r.geometry("500x500")
                            I1=PhotoImage(file="MS1.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 1000').grid(row=1,column=0)
                            r.mainloop()
                        def se2():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="MS2.gif")
                            lb=Label(r,image=I1)
                            Label(r,text='PRICE 1100').grid(row=1,column=0)
                            lb.grid(row=0,column=0) 
                            r.mainloop()
                        Label(R,text="           ").grid(row=4,column=1)
                        Label(R,text="           ").grid(row=5,column=1)
                        Label(R,text="           ").grid(row=6,column=1)
                        Label(R,text="           ").grid(row=7,column=1)
                        Label(R,text="           ").grid(row=8,column=1)
                        Label(R,text="           ").grid(row=9,column=1)
                        Label(R,text="           ").grid(row=10,column=1)
                        Label(R,text="           ").grid(row=11,column=1)
                        Label(R,text="           ").grid(row=12,column=1)
                        Label(R,text="           ").grid(row=13,column=1)
                        Label(R,text="           ").grid(row=14,column=1)
                        Label(R,text="           ").grid(row=15,column=1)
                        Button(R,text='VIEW',command=st1).grid(row=4,column=2)
                        Button(R,text='VIEW',command=st2).grid(row=7,column=2)
                        Button(R,text='VIEW',command=se1).grid(row=10,column=2)
                        Button(R,text='VIEW',command=se2).grid(row=13,column=2)
                        def atc1():
                            r=ema.get()
                            f=' Item1 '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atc2():
                            r=ema.get()
                            f=' Item2 '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atc3():
                            r=ema.get()
                            f=' Item3 '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atc4():
                            r=ema.get()
                            f=' Item4 '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def continu():
                            y=Tk()
                            y.geometry("300x300")
                            Label(y,text='PAYMENT',font='Times 20',fg='black').grid(row=0,column=0)
                            def pay1():
                                o=Tk()
                                o.geometry("300x300") 
                                Label(o,text='ORDER WILL BE DELIEVERED TO YOUR ADDRESS').grid(row=0,column=0)
                                o.mainloop()
                            def pay2():
                                pa=Tk()
                                pa.geometry("350x350")
                                Label(pa,text='ADD MONEY TO THE PAYTM NUMBER 9981834317').grid(row=0,column=0)
                                pa.mainloop()      
                            Button(y,text='Cash On Delievery',font='Times  10',fg='green',command=pay1).grid(row=1,column=0)
                            Button(y,text='Paytm',font='Times 10',fg='green',command=pay2).grid(row=1,column=1)
                            y.mainloop()
                        Label(R,text="           ").grid(row=4,column=3)
                        Label(R,text="           ").grid(row=5,column=3)
                        Label(R,text="           ").grid(row=6,column=3)
                        Label(R,text="           ").grid(row=7,column=3)
                        Label(R,text="           ").grid(row=8,column=3)
                        Label(R,text="           ").grid(row=9,column=3)
                        Label(R,text="           ").grid(row=10,column=3)
                        Label(R,text="           ").grid(row=11,column=3)
                        Label(R,text="           ").grid(row=12,column=3)
                        Label(R,text="           ").grid(row=13,column=3)
                        Label(R,text="           ").grid(row=14,column=3)
                        Label(R,text="           ").grid(row=15,column=3)
                        Button(R,text='ADD TO CART',command=atc1).grid(row=4,column=4)
                        Button(R,text='ADD TO CART',command=atc2).grid(row=7,column=4)
                        Button(R,text='ADD TO CART',command=atc3).grid(row=10,column=4)
                        Button(R,text='ADD TO CART',command=atc4).grid(row=13,column=4)
                        Button(R,text='CONTINUE',command=continu).grid(row=14,column=4)
                        R.mainloop()
                    def womenord():
                        Rw=Tk()
                        Rw.geometry("400x400")
                        Label(Rw,text="").grid(row=0,column=0)
                        Label(Rw,text="").grid(row=1,column=0) 
                        Label(Rw,text=" Click View To View An Item",font='Times 20',fg='red').grid(row=2,column=0,columnspan=15)
                        Label(Rw,text=" Click Add To Cart To Order",font='Times 20',fg='red').grid(row=3,column=0,columnspan=15) 
                        Label(Rw,text='  Shirt 1').grid(row=4,column=0)
                        Label(Rw,text="").grid(row=5,column=0)
                        Label(Rw,text="").grid(row=6,column=0)
                        Label(Rw,text='  Shirt 2').grid(row=7,column=0)
                        Label(Rw,text="").grid(row=8,column=0)
                        Label(Rw,text="").grid(row=9,column=0)
                        Label(Rw,text='  Shoe 1').grid(row=10,column=0)
                        Label(Rw,text="").grid(row=11,column=0)
                        Label(Rw,text="").grid(row=12,column=0)
                        Label(Rw,text='  Shoe 2').grid(row=13,column=0)
                        def stw1():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="WC1.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 700').grid(row=1,column=0)
                            r.mainloop()
                        def stw2():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="WC2.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 800').grid(row=1,column=0)
                            r.mainloop()
                        def sew1():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="WS1.gif")
                            lb=Label(r,image=I1)
                            lb.grid(row=0,column=0)
                            Label(r,text='PRICE 1000').grid(row=1,column=0)
                            r.mainloop()
                        def sew2():
                            r=Toplevel()
                            r.geometry("300x300")
                            I1=PhotoImage(file="WS2.gif")
                            lb=Label(r,image=I1)
                            Label(r,text='PRICE 1100').grid(row=1,column=0)
                            lb.grid(row=0,column=0) 
                            r.mainloop() 
                        Label(Rw,text="           ").grid(row=4,column=1)
                        Label(Rw,text="           ").grid(row=5,column=1)
                        Label(Rw,text="           ").grid(row=6,column=1)
                        Label(Rw,text="           ").grid(row=7,column=1)
                        Label(Rw,text="           ").grid(row=8,column=1)
                        Label(Rw,text="           ").grid(row=9,column=1)
                        Label(Rw,text="           ").grid(row=10,column=1)
                        Label(Rw,text="           ").grid(row=11,column=1)
                        Label(Rw,text="           ").grid(row=12,column=1)
                        Label(Rw,text="           ").grid(row=13,column=1)
                        Label(Rw,text="           ").grid(row=14,column=1)
                        Label(Rw,text="           ").grid(row=15,column=1)
                        Button(Rw,text='VIEW',command=stw1).grid(row=4,column=2)
                        Button(Rw,text='VIEW',command=stw2).grid(row=7,column=2)
                        Button(Rw,text='VIEW',command=sew1).grid(row=10,column=2)
                        Button(Rw,text='VIEW',command=sew2).grid(row=13,column=2)
                        def atcw1():
                            r=ema.get()
                            f=' Item1_w '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atcw2():
                            r=ema.get()
                            f=' Item2_w '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atcw3():
                            r=ema.get()
                            f=' Item3_w '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        def atcw4():
                            r=ema.get()
                            f=' Item4_w '
                            d=[r,f]
                            cur.execute("insert into cusord(EmailU,orde) values(?,?)",d)
                            con.commit()
                        Label(Rw,text="           ").grid(row=4,column=3)
                        Label(Rw,text="           ").grid(row=5,column=3)
                        Label(Rw,text="           ").grid(row=6,column=3)
                        Label(Rw,text="           ").grid(row=7,column=3)
                        Label(Rw,text="           ").grid(row=8,column=3)
                        Label(Rw,text="           ").grid(row=9,column=3)
                        Label(Rw,text="           ").grid(row=10,column=3)
                        Label(Rw,text="           ").grid(row=11,column=3)
                        Label(Rw,text="           ").grid(row=12,column=3)
                        Label(Rw,text="           ").grid(row=13,column=3)
                        Label(Rw,text="           ").grid(row=14,column=3)
                        Label(Rw,text="           ").grid(row=15,column=3)
                        def continu():
                            j=Tk()
                            j.geometry("300x300")
                            Label(j,text='PAYMENT',font='Times 20',fg='black').grid(row=0,column=0)
                            def pay1():
                                f=Tk()
                                f.geometry("300x300")
                                Label(f,text='ORDER WILL BE DELIEVERED TO YOUR ADDRESS').grid(row=0,column=0)
                                f.mainloop()
                            def pay2():
                                pat=Tk()
                                pat.geometry("350x350")
                                Label(pat,text='ADD MONEY TO THE PAYTM NUMBER 9981834317').grid(row=0,column=0)      
                                pat.mainloop()      
                            Button(j,text='Cash On Delievery',font='Times  10',fg='green',command=pay1).grid(row=1,column=0)
                            Button(j,text='Paytm',font='Times 10',fg='green',command=pay2).grid(row=1,column=1)
                            j.mainloop()
                        Button(Rw,text='ADD TO CART',command=atcw1).grid(row=4,column=4)
                        Button(Rw,text='ADD TO CART',command=atcw2).grid(row=7,column=4)
                        Button(Rw,text='ADD TO CART',command=atcw3).grid(row=10,column=4)
                        Button(Rw,text='ADD TO CART',command=atcw4).grid(row=13,column=4)
                        Button(Rw,text='CONTINUE',command=continu).grid(row=14,column=4) 
                        Rw.mainloop()
                    Label(OT,text="  For Men",fg='grey',font='Times 18').grid(row=6,column=2)
                    Label(OT,text="").grid(row=7,column=0)
                    Label(OT,text="").grid(row=8,column=0)
                    Button(OT,text='MEN',font='Times 18',fg='black',command=menord).grid(row=9,column=2)
                    Label(OT,text="").grid(row=10,column=0)
                    Label(OT,text="").grid(row=11,column=0)
                    Label(OT,text="").grid(row=12,column=0)
                    Label(OT,text="  For Women",fg='grey',font='Times 18').grid(row=13,column=2)
                    Label(OT,text="").grid(row=14,column=0)
                    Label(OT,text="").grid(row=15,column=0)
                    Button(OT,text='WOMEN',font='Times 18',fg='black',command=womenord).grid(row=16,column=2)
                    OT.mainloop()
                else:
                    Label(ROTN,text="Invalid username or password", fg="red",font='Times 20').grid(row=11,column=0)
        Label(ROTN,text="").grid(row=8,column=0)
        Label(ROTN,text="").grid(row=9,column=0)
        Button(ROTN,text=' LOGIN ',fg='black',command=lgn).grid(row=10,column=1)
        ROTN.mainloop()
    def al():
        P=Tk()
        P.geometry("600x300")
        Label(P,text="").grid(row=0,column=0)
        Label(P,text="").grid(row=1,column=0)
        Label(P,text="  WELCOME ADMINISTRATOR  ",font='Times 20',fg='orange').grid(row=2,column=0)
        Label(P,text="").grid(row=3,column=0)
        Label(P,text='  USERNAME:  ',fg='black').grid(row=4,column=0)
        Label(P,text="").grid(row=5,column=0)
        Label(P,text="").grid(row=6,column=0)
        Label(P,text='  PASSWORD:  ',fg='black').grid(row=7,column=0)
        aema=Entry(P)
        aema.grid(row=4,column=1)
        apas=Entry(P,show="*")
        apas.grid(row=7,column=1)
        def algn():
            if aema.get() == "" or apas.get() == "":
                Label(P,text='Please Fill The Required fields',fg='RED',font='Times 10').grid(row=8,column=0)
            else:
                cur.execute("SELECT * FROM member WHERE EmailU = ? AND Password = ?", (aema.get(), apas.get()))
                if cur.fetchone() is not None:
                    U=Tk()
                    U.geometry("400x500")
                    Label(U,text="").grid(row=0,column=0)
                    Label(U,text="").grid(row=1,column=0)
                    Label(U,text="  SELECT YOUR CHOICE",font='Times 19',fg='orange').grid(row=2,column=0)
                    Label(U,text="").grid(row=3,column=0)
                    Label(U,text='SEE MEMBERS DETAILS',font='Times 12',fg='brown').grid(row=4,column=0)
                    Label(U,text="").grid(row=5,column=0)
                    Label(U,text="").grid(row=6,column=0)
                    Label(U,text='SEE ORDER DETAILS',font='Times 12',fg='brown').grid(row=7,column=0)
                    Label(U,text="").grid(row=8,column=0)
                    Label(U,text="").grid(row=9,column=0)
                    Label(U,text='DELETE MEMBERS DETAILS',font='Times 12',fg='brown').grid(row=10,column=0)
                    Label(U,text="").grid(row=11,column=0)
                    Label(U,text="").grid(row=12,column=0)
                    Label(U,text='DELETE ORDER DETAILS',font='Times 12',fg='brown').grid(row=13,column=0)
                    def memdet():
                        cur.execute("select * from member")
                        md=cur.fetchall()
                        if md is not None:
                            MDE=Tk()
                            MDE.geometry("2000x2000")
                            Label(MDE,text=md).grid(row=0,column=0)
                            MDE.mainloop()
                        else:
                            Label(U,text='NO MEMBER DETAIL ',font='Times 10',fg='black').grid(row=15,column=0)
                    def orddet():
                        cur.execute("select * from cusord")
                        od=cur.fetchall()
                        if od is not None:
                            showinfo('Information',od)
                        else:
                            Label(U,text='NO ORDER AVAILABLE ',font='Times 10',fg='black').grid(row=16,column=0)
                    def memdel():
                        cur.execute("delete from member")
                        con.commit()
                    def orddel():
                        cur.execute("delete from cusord")
                        con.commit()
                    Button(U,text='VIEW',command=memdet).grid(row=4,column=2)
                    Button(U,text='VIEW',command=orddet).grid(row=7,column=2)
                    Button(U,text='DELETE',command=memdel).grid(row=10,column=2)
                    Button(U,text='DELETE',command=orddel).grid(row=13,column=2)                
                    U.mainloop()
                else:
                    Label(P,text="Invalid Username Or Password",fg='red',font='Times 10').grid(row=14,column=1)
        Label(P,text="").grid(row=8,column=0)
        Button(P,text='LOGIN',command=algn).grid(row=9,column=1)
    Label(root,text="").grid(row=10,column=0)
    Label(root,text="").grid(row=11,column=0)    
    Button(root,text=' LOGIN ',font='Times 10',fg='black',command=login).grid(row=12,column=0)
    Label(root,text="").grid(row=13,column=0)
    Label(root,text="").grid(row=14,column=0)
    Button(root,text=' SIGN UP ',font='Times 10',fg='black',command=signupgui).grid(row=15,column=0)
    Label(root,text="").grid(row=16,column=0)
    Label(root,text="").grid(row=17,column=0)
    Button(root,text=' Check Your Account Details ',fg='black',command=CHK).grid(row=18,column=0)
    Label(root,text="").grid(row=19,column=0)
    Label(root,text="").grid(row=20,column=0)
    Button(root,text=' Administrator Login ',font='Times 10',fg='black',command=al).grid(row=21,column=0)

    root.mainloop()
lb=Label(roots,image=img1)
lb.bind('<Motion>',fun)
lb.pack()
roots.mainloop()
